In [1]:
%load_ext autoreload
%autoreload 2

In [5]:
import sys
import json
import pandas as pd
import os

In [3]:
census = pd.read_csv('https://raw.githubusercontent.com/alan-turing-institute/reprosyn/main/src/reprosyn/datasets/2011-census-microdata/2011-census-microdata-small.csv')
census = census.drop(columns = ['Person ID'])
census.head()

,Region,Residence Type,Family Composition,Population Base,Sex,Age,Marital Status,Student,Country of Birth,Health,Ethnic Group,Religion,Economic Activity,Occupation,Industry,Hours worked per week,Approximated Social Grade
0,E12000001,H,2,1,2,6,2,2,1,2,1,2,5,8,2,-9,4
1,E12000001,H,5,1,1,4,1,2,1,1,1,2,1,8,6,4,3
2,E12000001,H,3,1,2,4,1,2,1,1,1,1,1,6,11,3,4
3,E12000001,H,3,1,2,2,1,2,1,2,1,2,1,7,7,3,2
4,E12000001,H,3,1,1,5,4,2,1,1,1,2,1,1,4,3,2

In [7]:
with open('../data/census.json', 'r') as f:
    census_description = json.load(f)

census_description

[{'name': 'Region',
  'type': 'finite',
  'representation': ['E12000001',
   'E12000002',
   'E12000003',
   'E12000004',
   'E12000005',
   'E12000009',
   'E12000006',
   'E12000008',
   'E12000007',
   'W92000004']},
 {'name': 'Residence Type', 'type': 'finite', 'representation': ['H', 'C']},
 {'name': 'Family Composition',
  'type': 'finite',
  'representation': ['-9', '1', '2', '3', '4', '5', '6']},
 {'name': 'Population Base',
  'type': 'finite',
  'representation': ['1', '2', '3']},
 {'name': 'Sex', 'type': 'finite', 'representation': ['1', '2']},
 {'name': 'Age',
  'type': 'finite',
  'representation': ['1', '2', '3', '4', '5', '6', '7', '8']},
 {'name': 'Marital Status',
  'type': 'finite',
  'representation': ['1', '2', '3', '4', '5']},
 {'name': 'Student', 'type': 'finite', 'representation': ['1', '2']},
 {'name': 'Country of Birth',
  'type': 'finite',
  'representation': ['-9', '1', '2']},
 {'name': 'Health',
  'type': 'finite',
  'representation': ['-9', '1', '2', '3', '4', '5']},
 {'name': 'Ethnic Group',
  'type': 'finite',
  'representation': ['-9', '1', '2', '3', '4', '5']},
 {'name': 'Religion',
  'type': 'finite',
  'representation': ['-9', '1', '2', '3', '4', '5', '6', '7', '8', '9']},
 {'name': 'Economic Activity',
  'type': 'finite',
  'representation': ['-9', '1', '2', '3', '4', '5', '6', '7', '8', '9']},
 {'name': 'Occupation',
  'type': 'finite',
  'representation': ['-9', '1', '2', '3', '4', '5', '6', '7', '8', '9']},
 {'name': 'Industry',
  'type': 'finite',
  'representation': ['-9',
   '1',
   '2',
   '3',
   '4',
   '5',
   '6',
   '7',
   '8',
   '9',
   '10',
   '11',
   '12']},
 {'name': 'Hours worked per week',
  'type': 'finite',
  'representation': ['-9', '1', '2', '3', '4']},
 {'name': 'Approximated Social Grade',
  'type': 'finite',
  'representation': ['-9', '1', '2', '3', '4']}]

In [8]:
from tapas.datasets import TabularDataset
from tapas.datasets.data_description import DataDescription

tab_census = TabularDataset(census.sample(10000), description = DataDescription(census_description))

In [13]:
from tapas.generators import ReprosynGenerator
from reprosyn.methods import MST

gen = ReprosynGenerator(MST, label="MST")
gen.fit(tab_census)

tab_data = gen.generate(10)
tab_data.data

,Region,Residence Type,Family Composition,Population Base,Sex,Age,Marital Status,Student,Country of Birth,Health,Ethnic Group,Religion,Economic Activity,Occupation,Industry,Hours worked per week,Approximated Social Grade
0,E12000001,H,2,1,1,6,2,2,1,1,1,2,1,5,2,4,4
1,E12000002,H,1,1,2,4,2,2,1,1,1,2,1,7,4,3,2
2,E12000005,H,-9,2,1,1,1,2,1,2,1,2,-9,-9,-9,-9,-9
3,E12000009,H,3,1,2,1,1,1,2,1,1,9,-9,-9,-9,-9,-9
4,E12000003,H,2,1,1,5,2,2,1,1,1,2,1,8,6,2,4
5,E12000009,H,2,1,1,3,2,2,1,1,1,2,7,-9,-9,-9,4
6,E12000005,H,4,1,1,2,1,2,1,2,1,2,1,2,11,3,1
7,E12000004,H,2,1,1,7,2,2,1,3,1,2,5,5,3,-9,3
8,E12000003,H,2,1,2,1,1,1,1,1,1,2,-9,-9,2,-9,-9
9,E12000003,H,2,1,2,3,1,2,1,2,1,1,1,9,5,3,3

In [14]:
datasets = [] 
samples = 10
epsilon = [1,10,100]
for e in epsilon:
    gen = ReprosynGenerator(MST, epsilon = e)
    gen.fit(TabularDataset(census, description = DataDescription(census_description)))
    tab_data = gen.generate(samples)
    datasets.append([gen, tab_data.data])

In [15]:
datasets

[[<tapas.generators.generator.ReprosynGenerator at 0x13f2a3280>,
        Region Residence Type Family Composition Population Base Sex Age  \
  0  E12000004              H                  5               1   1   7
  1  E12000009              H                  2               1   1   5
  2  E12000002              H                  2               1   2   1
  3  E12000001              H                  2               1   2   4
  4  E12000004              H                  1               1   2   5
  5  E12000004              H                  2               1   1   8
  6  E12000001              H                  5               1   2   4
  7  E12000003              H                  2               1   2   7
  8  E12000009              H                  2               1   1   1
  9  E12000003              H                  2               1   2   5

    Marital Status Student Country of Birth Health Ethnic Group Religion  \
  0              4       2                1      1            1        2
  1              2       2                2      1            5        2
  2              1       1                1      1            1        2
  3              2       2                1      2            1        2
  4              1       2                2      1            5        3
  5              2       2                1      3            1        1
  6              1       2                1      2            1        1
  7              2       2                1      3            1        1
  8              1       1                1      2            1        1
  9              2       2                1      4            1        2

    Economic Activity Occupation Industry Hours worked per week  \
  0                 1          3        7                     3
  1                 1          6        6                     3
  2                -9         -9       -9                    -9
  3                 3          4        2                    -9
  4                 3          6       12                    -9
  5                 1          5        4                     1
  6                 1          3        2                     4
  7                 5          9       10                    -9
  8                -9         -9       -9                    -9
  9                 8          6       11                    -9

    Approximated Social Grade
  0                         1
  1                         3
  2                        -9
  3                         1
  4                         4
  5                         3
  6                         2
  7                         4
  8                        -9
  9                         3  ],
 [<tapas.generators.generator.ReprosynGenerator at 0x11d7072e0>,
        Region Residence Type Family Composition Population Base Sex Age  \
  0  E12000001              H                  1               1   1   8
  1  E12000009              H                  2               1   2   6
  2  E12000001              H                  2               1   2   6
  3  E12000004              H                  2               1   1   3
  4  E12000009              H                  2               1   2   5
  5  E12000003              H                  3               1   1   3
  6  E12000002              H                  2               1   2   1
  7  E12000009              H                  1               1   1   1
  8  E12000003              H                  2               1   2   7
  9  E12000003              H                  2               1   2   2

    Marital Status Student Country of Birth Health Ethnic Group Religion  \
  0              5       2                1      2            1        1
  1              2       2                1      1            1        2
  2              2       2                1      1            1        2
  3              2       2                2      1            1        2
  4              2       2                1      2            1        2
  5              1       2                1      1            1        1
  6              1       2                1      1            1        2
  7              1       1                1      1            1        1
  8              2       2                1      3            1        2
  9              1       1                1      1            1        2

    Economic Activity Occupation Industry Hours worked per week  \
  0                 7          1        4                    -9
  1                 5          2       11                    -9
  2                 1          7        5                     4
  3                 1          2        2                     3
  4                 1         -9       -9                     1
  5                 2          8        6                     3
  6                -9         -9       -9                    -9
  7                -9         -9       -9                    -9
  8                 5          5        4                    -9
  9                 6          2       10                     3

    Approximated Social Grade
  0                         1
  1                         1
  2                         2
  3                         1
  4                         4
  5                         4
  6                        -9
  7                        -9
  8                         4
  9                         2  ],
 [<tapas.generators.generator.ReprosynGenerator at 0x13f2a29e0>,
        Region Residence Type Family Composition Population Base Sex Age  \
  0  E12000002              H                  2               1   2   2
  1  E12000009              H                  2               1   2   8
  2  E12000003              H                  2               1   2   6
  3  E12000002              H                  2               1   1   6
  4  E12000001              H                  2               1   1   5
  5  E12000005              H                  1               1   2   5
  6  E12000004              H                  3               1   1   1
  7  E12000004              H                  5               1   2   3
  8  E12000004              H                  5               1   1   3
  9  E12000003              H                  2               1   1   4

    Marital Status Student Country of Birth Health Ethnic Group Religion  \
  0              1       2                2      2            4        2
  1              2       2                1      2            1        2
  2              2       2                1      2            1        2
  3              1       2                2      4            3        7
  4              2       2                1      1            1        2
  5              3       2                1      4            1        2
  6              1       1                1      1            1        2
  7              3       2                1      1            3        4
  8              1       2                1      2            1        1
  9              2       2                1      1            1        1

    Economic Activity Occupation Industry Hours worked per week  \
  0                 3          7        8                    -9
  1                 5         -9       -9                    -9
  2                 1          5        2                     4
  3                 5          8        5                    -9
  4                 1          1       12                     3
  5                 3          6       10                    -9
  6                -9         -9       -9                    -9
  7                 1          9        3                     2
  8                 1          7        4                     3
  9                 1          9       11                     3

    Approximated Social Grade
  0                         4
  1                         2
  2                         4
  3                         4
  4                         1
  5                         2
  6                        -9
  7                         3
  8                         2
  9                         4  ]]