In [1]:
%load_ext autoreload
%autoreload 2

In [3]:
import sys
import json
import pandas as pd

In [4]:
census = pd.read_csv('https://raw.githubusercontent.com/alan-turing-institute/reprosyn/main/src/reprosyn/datasets/2011-census-microdata/2011-census-microdata-small.csv')
census = census.drop(columns = ['Person ID'])
census.head()

,Region,Residence Type,Family Composition,Population Base,Sex,Age,Marital Status,Student,Country of Birth,Health,Ethnic Group,Religion,Economic Activity,Occupation,Industry,Hours worked per week,Approximated Social Grade
0,E12000001,H,2,1,2,6,2,2,1,2,1,2,5,8,2,-9,4
1,E12000001,H,5,1,1,4,1,2,1,1,1,2,1,8,6,4,3
2,E12000001,H,3,1,2,4,1,2,1,1,1,1,1,6,11,3,4
3,E12000001,H,3,1,2,2,1,2,1,2,1,2,1,7,7,3,2
4,E12000001,H,3,1,1,5,4,2,1,1,1,2,1,1,4,3,2

In [5]:
with open('/Users/zoe/Desktop/Benchmarking-of-Tabular-Synthetic-Data-Generation/privacy/data/census.json', 'r') as f:
    census_description = json.load(f)

census_description

[{'name': 'Region',
  'type': 'finite',
  'representation': ['E12000001',
   'E12000002',
   'E12000003',
   'E12000004',
   'E12000005',
   'E12000009',
   'E12000006',
   'E12000008',
   'E12000007',
   'W92000004']},
 {'name': 'Residence Type', 'type': 'finite', 'representation': ['H', 'C']},
 {'name': 'Family Composition',
  'type': 'finite',
  'representation': ['-9', '1', '2', '3', '4', '5', '6']},
 {'name': 'Population Base',
  'type': 'finite',
  'representation': ['1', '2', '3']},
 {'name': 'Sex', 'type': 'finite', 'representation': ['1', '2']},
 {'name': 'Age',
  'type': 'finite',
  'representation': ['1', '2', '3', '4', '5', '6', '7', '8']},
 {'name': 'Marital Status',
  'type': 'finite',
  'representation': ['1', '2', '3', '4', '5']},
 {'name': 'Student', 'type': 'finite', 'representation': ['1', '2']},
 {'name': 'Country of Birth',
  'type': 'finite',
  'representation': ['-9', '1', '2']},
 {'name': 'Health',
  'type': 'finite',
  'representation': ['-9', '1', '2', '3', '4', '5']},
 {'name': 'Ethnic Group',
  'type': 'finite',
  'representation': ['-9', '1', '2', '3', '4', '5']},
 {'name': 'Religion',
  'type': 'finite',
  'representation': ['-9', '1', '2', '3', '4', '5', '6', '7', '8', '9']},
 {'name': 'Economic Activity',
  'type': 'finite',
  'representation': ['-9', '1', '2', '3', '4', '5', '6', '7', '8', '9']},
 {'name': 'Occupation',
  'type': 'finite',
  'representation': ['-9', '1', '2', '3', '4', '5', '6', '7', '8', '9']},
 {'name': 'Industry',
  'type': 'finite',
  'representation': ['-9',
   '1',
   '2',
   '3',
   '4',
   '5',
   '6',
   '7',
   '8',
   '9',
   '10',
   '11',
   '12']},
 {'name': 'Hours worked per week',
  'type': 'finite',
  'representation': ['-9', '1', '2', '3', '4']},
 {'name': 'Approximated Social Grade',
  'type': 'finite',
  'representation': ['-9', '1', '2', '3', '4']}]

In [6]:
from tapas.datasets import TabularDataset
from tapas.datasets.data_description import DataDescription

In [7]:
tab_census = TabularDataset(census.sample(10000), description = DataDescription(census_description))

In [8]:
from tapas.generators import ReprosynGenerator

In [9]:
from reprosyn.methods import MST

In [10]:
gen = ReprosynGenerator(MST, label="MST")

In [11]:
gen.fit(tab_census)

In [12]:
tab_data = gen.generate(10)
tab_data.data

,Region,Residence Type,Family Composition,Population Base,Sex,Age,Marital Status,Student,Country of Birth,Health,Ethnic Group,Religion,Economic Activity,Occupation,Industry,Hours worked per week,Approximated Social Grade
0,E12000003,H,3,1,2,4,3,2,1,2,1,1,1,9,2,2,3
1,E12000005,H,2,1,2,3,2,2,2,4,1,2,3,6,6,-9,4
2,E12000004,H,1,1,1,1,1,1,1,1,4,6,-9,-9,-9,-9,-9
3,E12000005,H,2,1,1,1,1,2,1,1,1,1,-9,-9,-9,-9,-9
4,E12000004,H,3,1,2,6,4,1,1,1,1,2,6,5,4,-9,2
5,E12000002,H,3,1,1,2,1,1,1,2,1,1,6,5,9,-9,3
6,E12000009,H,2,1,2,1,1,1,1,5,1,2,-9,-9,-9,-9,-9
7,E12000001,H,2,1,2,5,2,2,1,1,1,1,1,7,4,4,1
8,E12000004,H,5,1,2,3,1,2,1,1,3,6,1,2,10,3,1
9,E12000003,H,2,1,1,6,2,2,1,2,1,1,1,9,8,3,4

In [13]:
datasets = [] 
samples = 10
epsilon = [1,10,100]
for e in epsilon:
    gen = ReprosynGenerator(MST, epsilon = e)
    gen.fit(TabularDataset(census, description = DataDescription(census_description)))
    tab_data = gen.generate(samples)
    datasets.append([gen, tab_data.data])

In [14]:
datasets

[[<tapas.generators.generator.ReprosynGenerator at 0x143022020>,
        Region Residence Type Family Composition Population Base Sex Age  \
  0  E12000002              H                  2               1   2   4
  1  E12000002              H                  1               1   2   1
  2  E12000001              H                  2               1   1   6
  3  E12000002              H                  5               2   1   2
  4  E12000009              H                  2               1   2   5
  5  E12000004              H                  2               1   2   6
  6  E12000009              H                  2               1   1   7
  7  E12000004              H                 -9               1   2   2
  8  E12000003              H                  3               1   1   4
  9  E12000002              H                  2               1   1   3

    Marital Status Student Country of Birth Health Ethnic Group Religion  \
  0              2       2                1      1            1        1
  1              1       1                1      1            1        9
  2              1       2                1      2            1        2
  3              1       2               -9      1           -9       -9
  4              2       2                1      2            1        1
  5              2       2                1      2            1        9
  6              2       2                1      1            1        2
  7              1       1                1      2            1        1
  8              1       2                1      1            1        2
  9              1       2                2      1            3        6

    Economic Activity Occupation Industry Hours worked per week  \
  0                 3          4        9                    -9
  1                -9         -9       -9                    -9
  2                 1         -9       -9                     1
  3                 9          7        4                    -9
  4                 1          3        2                     2
  5                 2          6        8                    -9
  6                 1          9       11                     3
  7                 6          9       10                    -9
  8                 1          9        5                     3
  9                 1          5        6                     3

    Approximated Social Grade
  0                         2
  1                        -9
  2                         2
  3                         4
  4                         2
  5                         2
  6                         4
  7                         2
  8                         4
  9                         3  ],
 [<tapas.generators.generator.ReprosynGenerator at 0x110443700>,
        Region Residence Type Family Composition Population Base Sex Age  \
  0  E12000001              H                  2               1   1   3
  1  E12000002              H                  2               1   2   5
  2  E12000004              H                  2               1   1   7
  3  E12000001              H                  3               1   2   2
  4  E12000003              H                  3               1   2   1
  5  E12000009              H                  2               1   2   1
  6  E12000002              H                  1               1   1   3
  7  E12000005              H                  1               1   1   8
  8  E12000009              H                  1               1   1   7
  9  E12000004              H                  5               1   1   1

    Marital Status Student Country of Birth Health Ethnic Group Religion  \
  0              2       2                1      2            3        6
  1              2       2                1      1            1        2
  2              2       2                2      3            1        2
  3              1       1                1      1            1        9
  4              1       1                1      2            1        2
  5              1       2                1      1            1        1
  6              1       2                1      2            1        1
  7              5       2                1      1            1        9
  8              4       2                1      3            1        2
  9              1       1                1      1            1        1

    Economic Activity Occupation Industry Hours worked per week  \
  0                 1          2       10                     3
  1                 1          9        5                     3
  2                 1          7        4                     2
  3                 4          2        2                    -9
  4                -9         -9       -9                    -9
  5                -9         -9       -9                    -9
  6                 7          8        6                    -9
  7                 5          9        8                    -9
  8                 5          5        3                    -9
  9                -9         -9       -9                    -9

    Approximated Social Grade
  0                         1
  1                         3
  2                         4
  3                         2
  4                        -9
  5                        -9
  6                         4
  7                         4
  8                         3
  9                        -9  ],
 [<tapas.generators.generator.ReprosynGenerator at 0x110442290>,
        Region Residence Type Family Composition Population Base Sex Age  \
  0  E12000003              H                  2               1   2   3
  1  E12000009              H                  2               1   1   5
  2  E12000003              H                  2               1   2   8
  3  E12000009              H                  3               1   2   2
  4  E12000009              H                  1               1   1   2
  5  E12000009              H                  2               1   2   4
  6  E12000004              H                  3               1   1   6
  7  E12000002              H                 -9               1   1   1
  8  E12000005              H                  1               1   2   8
  9  E12000002              H                  2               1   2   1

    Marital Status Student Country of Birth Health Ethnic Group Religion  \
  0              1       2                1      2            1        1
  1              2       2                2      1            2        2
  2              2       2                1      2            1        2
  3              1       1                1      1            1        2
  4              1       2                1      1            1        1
  5              2       2                1      2            1        9
  6              2       2                1      1            1        2
  7              1       1                1      1            1        2
  8              5       2                1      5            1        2
  9              1       1                1      2            1        1

    Economic Activity Occupation Industry Hours worked per week  \
  0                 1          4        9                     3
  1                 1          8        2                     4
  2                 9          9        8                    -9
  3                 4          6       11                     1
  4                 9          5        3                    -9
  5                 2          7        4                     3
  6                 1          9       10                     1
  7                -9         -9       -9                    -9
  8                 5          9        5                    -9
  9                -9         -9       -9                    -9

    Approximated Social Grade
  0                         2
  1                         4
  2                         4
  3                         4
  4                         3
  5                         4
  6                         4
  7                        -9
  8                         4
  9                        -9  ]]